export const reduxTypes = {
  IS_USER_LOGIN: 'IS_USER_LOGIN',
  PROFILE_DATA: 'PROFILE_DATA',
  RESET_DATA: 'RESET_DATA',
  THEME_MODE: 'THEME_MODE',
  UPDATE_PROFILE_NAME: 'UPDATE_PROFILE_NAME',
  SIGN_OUT: 'SIGN_OUT'
};
